[project]
name = "SnappySTEP"
version = "0.0.1"

[project.scripts]
snappyStep = "snappy_step:main_func"
snappyStepConfig = "snappy_step:write_snappy_step_dict_template"


[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"