[MESH] # GMSH surface mesh options
MeshSizeMax = 1e22
MeshSizeMin = 0
MeshSizeFactor = 1
MeshSizeFromCurvature = 0
MeshAlgorithm = 6
# 1: MeshAdapt, 2: Automatic, 3: Initial mesh only, 5: Delaunay, 6: Frontal-Delaunay, 7: BAMG, 8: Frontal-Delaunay for Quads, 9: Packing of Parallelograms, 11: Quasi-structured Quad
# GMSH default is 6: Frontal-Dlaunay

[GEOMETRY] # Not implimented yet
PreProcessSequence = ["none"]
# Optionally enter sequence of geometry processing steps. See Gmsh documentation for details. Seperate entires in array by comma.
# fixDegenerated fixSmallEdges fixSmallFaces sewFaces makeSolids defeature
Scaling = 1
# Geometry.OCCScaling
InsidePointOffset = "default"
