[MESH]
MeshSizeMax = 0.5
MeshSizeMin = 0
MeshSizeFactor = 1
MeshSizeFromCurvature = 0
MeshAlgorithm = 6
# 1: MeshAdapt, 2: Automatic, 3: Initial mesh only, 5: Delaunay, 6: Frontal-Delaunay, 7: BAMG, 8: Frontal-Delaunay for Quads, 9: Packing of Parallelograms, 11: Quasi-structured Quad
# GMSH default is 6: Frontal-Dlaunay
EdgeMesh = true

[GEOMETRY]
Scaling = 1


#[insidePoint] # if volume is not listed, a suitible point will be determined
#obj = [0.01, 0.190, 0.05]

[sHM]
multiRegionFeatureSnap = true